#!/bin/sh

# xinitrc runs automatically when you run startx

# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
# . /etc/X11/Xsession

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config/x11/xprofile" ]; then 
    . "${XDG_CONFIG_HOME:-$HOME/.config/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

