#!/bin/sh

# source profile - this should have most common environment variables
[ -f ~/.profile ] && . ~/.profile

# variables that are specific to the xsession go here
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
