#!/bin/sh

echo "Starting xsession: $(date)"

# user the Xresources file
xrdb ${}/x11/xresources & xrdbpid=$1

autostart="compton ssh-agent"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec dwm