#!/bin/sh

echo "Starting xsession: $(date)"

# user the Xresources file
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$1

autostart="compton ssh-agent mpd"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec dwm